### ISSUE TITLE
Kibana 4.5 inquiry.

### ISSUE THREAD

**Issue by ThomasFlanaghan** [raystorm-place/kibana-slider-plugin#1]
Hi,

This looks very useful and It would be great to use but I am currently using Kibana 4.5 and it says it is compatible with 4.4. 
How feasible would it be for this to work on 4.5? And do you ever plan to release an update for 4.5 or 5?

**Comment by raystorm-place** [comment]
The plugin is also compatible with kibana 4.5 and was already successfully used in production.
