### ISSUE TITLE
Plugin does not work with decimal places

### ISSUE THREAD

**Issue by ThomasFlanaghan** [raystorm-place/kibana-slider-plugin#2]
Hi, 

I am trying to use the slider plugin for decimal places e.g. 0 - 1 with a 0.1 step however this does not work. I tried fiddling about with the precision but I think it's due to some rounding code. Could you advise on how to rectify this? 

Thanks

**Comment by raystorm-place** [comment]
The slider plugin depends on angularjs-slider. It seems that angularjs-slider currently doesnt support floating steps. But i leave the ticket open for future enhancements.

Thanks

**Comment by ThomasFlanaghan** [comment]
Adding precision: 1 in the options under slidercontroller.js fixed the issue. You can also set it to 2 for two decimal places.

**Comment by raystorm-place** [comment]
Thanks! The fix is in the master now
