### ISSUE TITLE
Slider only works on the default index

### ISSUE THREAD

**Issue by chrisdrusso** [raystorm-place/kibana-slider-plugin#4]
When working with multiple indices, there is currently no way to add a slider widget to an index other than the default index.

**Comment by raystorm-place** [comment]
I fixed this in master. Thanks

**Comment by chrisdrusso** [comment]
Seems it still doesn't work for non-default indexes.

**Comment by raystorm-place** [comment]
The change is in the master. You must first remove your old plugin, and reinstall it from master.

**Comment by chrisdrusso** [comment]
It's working.  I must've had an old file cached.  I love it.  Thanks
