### ISSUE TITLE
Allow to set the limits in the dashboards themselves

### ISSUE THREAD

**Issue by jccq** [raystorm-place/kibana-slider-plugin#6]
An advanced user might want to change the limit from the UI e.g. doubleclicking on the numbers, being able to set a different limit. This is very useful in conjunction with https://github.com/raystorm-place/kibana-slider-plugin/issues/5 and in case of outlayers in the data. e.g. typically all values are from 0 to 100 then there is this one record that has 100000 ..

**Comment by raystorm-place** [comment]
When you configure min and max probably then you can use simple the slide feature. I currently see no real benefit. You can send a pull request, then i will check the feature. Thanks!
